### ISSUE TITLE
Engine crash with grangermaze 0.5+1

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1002]
Test map:

- http://dl.zittrig.eu/pkg/map-grangermaze_0.5%2B1.dpk

Backtrace:

```
Thread 1 "daemon" received signal SIGSEGV, Segmentation fault.
RB_RenderDrawSurfaces (fromSort=fromSort@entry=shaderSort_t::SS_ENVIRONMENT_FOG, toSort=toSort@entry=shaderSort_t::SS_OPAQUE, drawSurfFilter=drawSurfFilter@entry=DRAWSURFACES_ALL) at Unvanquished/daemon/src/engine/renderer/tr_backend.cpp:870
870			} else if( !( entity->e.renderfx & RF_DEPTHHACK ) ) {

Thread 1 (Thread 0x7ffff5517a80 (LWP 457030) "daemon"):
#0  RB_RenderDrawSurfaces (fromSort=fromSort@entry=shaderSort_t::SS_ENVIRONMENT_FOG, toSort=toSort@entry=shaderSort_t::SS_OPAQUE, drawSurfFilter=drawSurfFilter@entry=DRAWSURFACES_ALL) at Unvanquished/daemon/src/engine/renderer/tr_backend.cpp:870
#1  0x000055555568c510 in RB_RenderView (depthPass=false) at Unvanquished/daemon/src/engine/renderer/tr_backend.cpp:4752
#2  DrawViewCommand::ExecuteSelf (this=0x7fffd6e92b94) at Unvanquished/daemon/src/engine/renderer/tr_backend.cpp:5640
#3  0x0000555555680479 in RB_ExecuteRenderCommands (data=<optimized out>) at Unvanquished/daemon/src/engine/renderer/tr_backend.cpp:5884
#4  0x000055555569e1c2 in RE_EndFrame (frontEndMsec=0x0, backEndMsec=0x0) at Unvanquished/daemon/src/engine/renderer/tr_cmds.cpp:889
#5  0x0000555555620a90 in SCR_UpdateScreen () at Unvanquished/daemon/src/engine/client/cl_scrn.cpp:327
#6  0x0000555555614fed in CL_Frame (msec=msec@entry=15) at Unvanquished/daemon/src/engine/client/cl_main.cpp:2094
#7  0x00005555555a970f in Com_Frame () at Unvanquished/daemon/src/engine/qcommon/common.cpp:1028
#8  0x00005555555a24e5 in main (argc=<optimized out>, argv=<optimized out>) at Unvanquished/daemon/src/engine/framework/System.cpp:755
```

**Comment by illwieckz** [comment]
Unfortunatly I don't get a way to reproduce it on request.

**Comment by illwieckz** [comment]
Here is a way to reproduce the bug:

```
daemon -set common.framerate.max 60 \
    +devmap grangermaze +delay 100f setviewpos -2792 889 68 -57 -12
```

**Comment by VReaperV** [comment]
#1031 seems to fix the cause of this issue, I can no longer reproduce it with the changes in #1004 commented out.
