### ISSUE TITLE
random segfault on map change

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#103]
we still suffer from random crashes on map change, I got it logged on gdb:

```gdb
Thread 31 "daemon" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff95140700 (LWP 29722)]
0x00007fff9d89fb25 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.3.so.0

Thread 31 (Thread 0x7fff95140700 (LWP 29722)):
#0  0x00007fff9d89fb25 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.3.so.0
#1  0x00007fff6a454095 in Rocket::Core::Lua::LuaEventListener::ProcessEvent (this=0x7fff6ce62020, event=...)
    at ./Unvanquished/libs/libRocket/Source/Core/Lua/LuaEventListener.cpp:128
#2  0x00007fff6a35de88 in Rocket::Core::EventDispatcher::TriggerEvents (this=0x7fff6cee2e70, event=0x7fff6f818390)
    at ./Unvanquished/libs/libRocket/Source/Core/EventDispatcher.cpp:182
#3  0x00007fff6a35dc2f in Rocket::Core::EventDispatcher::DispatchEvent (this=0x7fff6cee2e70, target_element=0x7fff6cd0ffa0, name=..., parameters=..., 
    interruptible=false) at ./Unvanquished/libs/libRocket/Source/Core/EventDispatcher.cpp:146
#4  0x00007fff6a329115 in Rocket::Core::Element::DispatchEvent (this=0x7fff6cd0ffa0, event=..., parameters=..., interruptible=false)
    at ./Unvanquished/libs/libRocket/Source/Core/Element.cpp:1053
#5  0x00007fff6a31b7ea in Rocket::Core::RKTEventFunctor::operator() (this=0x7fff9513ea40, element=...)
    at ./Unvanquished/libs/libRocket/Source/Core/EventIterators.h:55
#6  0x00007fff6a31cbbe in std::for_each<__gnu_cxx::__normal_iterator<Rocket::Core::ElementReference*, std::vector<Rocket::Core::ElementReference, std::allocator<Rocket::Core::ElementReference> > >, Rocket::Core::RKTEventFunctor> (__first={element = 0x7fff6cd0ffa0}, __last={element = 0x7fff6fddf3f0}, __f=...)
    at /usr/include/c++/7/bits/stl_algo.h:3884
#7  0x00007fff6a31b593 in Rocket::Core::Context::SendEvents (old_items=std::set with 3 elements = {...}, new_items=std::set with 0 elements, event=..., 
    parameters=..., interruptible=false) at ./Unvanquished/libs/libRocket/Source/Core/Context.cpp:1221
#8  0x00007fff6a319c42 in Rocket::Core::Context::OnFocusChange (this=0x7fff7d2319a0, new_focus=0x7fff6cd0ffa0)
    at ./Unvanquished/libs/libRocket/Source/Core/Context.cpp:913
#9  0x00007fff6a328f3a in Rocket::Core::Element::Focus (this=0x7fff6cd0ffa0)
    at ./Unvanquished/libs/libRocket/Source/Core/Element.cpp:991
#10 0x00007fff6a31725d in Rocket::Core::Context::UnloadDocument (this=0x7fff7d2319a0, _document=0x7fff7d6ebe10)
    at ./Unvanquished/libs/libRocket/Source/Core/Context.cpp:309
#11 0x00007fff6a317430 in Rocket::Core::Context::UnloadAllDocuments (this=0x7fff7d2319a0)
    at ./Unvanquished/libs/libRocket/Source/Core/Context.cpp:327
#12 0x00007fff6a3162fc in Rocket::Core::Context::~Context (this=0x7fff7d2319a0, __in_chrg=<optimized out>)
    at ./Unvanquished/libs/libRocket/Source/Core/Context.cpp:82
#13 0x00007fff6a316508 in Rocket::Core::Context::~Context (this=0x7fff7d2319a0, __in_chrg=<optimized out>)
    at ./Unvanquished/libs/libRocket/Source/Core/Context.cpp:98
#14 0x00007fff6a427cea in Rocket::Core::ContextInstancerDefault::ReleaseContext (this=0x7fff7d838750, context=0x7fff7d2319a0)
    at ./Unvanquished/libs/libRocket/Source/Core/ContextInstancerDefault.cpp:52
#15 0x00007fff6a31b655 in Rocket::Core::Context::OnReferenceDeactivate (this=0x7fff7d2319a0)
    at ./Unvanquished/libs/libRocket/Source/Core/Context.cpp:1228
#16 0x00007fff6a396b13 in Rocket::Core::ReferenceCountable::RemoveReference (this=0x7fff7d2319a0)
    at ./Unvanquished/libs/libRocket/Source/Core/ReferenceCountable.cpp:73
#17 0x00007fff6a1ff1f8 in Rocket_Shutdown () at ./Unvanquished/src/cgame/rocket/rocket.cpp:403
#18 0x00007fff6a182461 in CG_Shutdown () at ./Unvanquished/src/cgame/cg_main.cpp:1611
#19 0x00007fff6a15280b in VM::<lambda()>::operator()(void) const (__closure=0x7fff9513f897)
    at ./Unvanquished/src/cgame/cg_api.cpp:73
#20 0x00007fff6a155836 in Util::apply_impl<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda()>, std::tuple<> >(VM::<lambda()> &&, std::tuple<> &&, Util::seq<>) (func=..., tuple=...) at ./Daemon/src/common/Util.h:138
#21 0x00007fff6a1551f4 in Util::apply<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda()>, std::tuple<> >(VM::<lambda()> &&, std::tuple<> &&) (func=..., 
    tuple=...) at ./Daemon/src/common/Util.h:143
#22 0x00007fff6a153f29 in IPC::detail::HandleMsg<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda()>, IPC::Message<IPC::Id<0, 2> >, IPC::Reply<> >(IPC::Channel &, IPC::SyncMessage<IPC::Message<IPC::Id<0, 2> >, IPC::Reply<> >, Util::Reader, VM::<lambda()> &&) (channel=..., reader=..., func=...)
    at ./Daemon/src/common/IPC/Channel.h:217
#23 0x00007fff6a1532ae in IPC::HandleMsg<IPC::SyncMessage<IPC::Message<IPC::Id<0, 2> > >, VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda()> >(IPC::Channel &, Util::Reader, VM::<lambda()> &&) (channel=..., reader=..., func=...) at ./Daemon/src/common/IPC/Channel.h:241
#24 0x00007fff6a152ba9 in VM::VMHandleSyscall (id=2, reader=...) at ./Unvanquished/src/cgame/cg_api.cpp:72
#25 0x00007fff6a2b749a in CommonInit (rootSocket=22) at ./Daemon/src/shared/VMMain.cpp:66
#26 0x00007fff6a2b75fe in vmMain (rootSocket=22) at ./Daemon/src/shared/VMMain.cpp:104
#27 0x00005555559316cd in VM::<lambda()>::operator()(void) const (__closure=0x55555e5b6008)
    at ./Daemon/src/engine/framework/VirtualMachine.cpp:352
#28 0x0000555555932c13 in std::__invoke_impl<void, VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::StringRef, VM::VMBase::InProcessInfo&)::<lambda()> >(std::__invoke_other, VM::<lambda()> &&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#29 0x00005555559329ba in std::__invoke<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::StringRef, VM::VMBase::InProcessInfo&)::<lambda()> >(VM::<lambda()> &&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#30 0x0000555555932e90 in std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::StringRef, VM::VMBase::InProcessInfo&)::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55555e5b6008) at /usr/include/c++/7/thread:234
#31 0x0000555555932e4c in std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::StringRef, VM::VMBase::InProcessInfo&)::<lambda()> > >::operator()(void) (this=0x55555e5b6008) at /usr/include/c++/7/thread:243
#32 0x0000555555932e1c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::StringRef, VM::VMBase::InProcessInfo&)::<lambda()> > > >::_M_run(void) (this=0x55555e5b6000) at /usr/include/c++/7/thread:186
#33 0x00007ffff46000ff in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#34 0x00007ffff3dbf7fc in start_thread (arg=0x7fff95140700) at pthread_create.c:465
#35 0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 18 (Thread 0x7fff9c223700 (LWP 27265)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fff9000864c)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fff90009c10, cond=0x7fff90008620) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7fff90008620, mutex=0x7fff90009c10) at pthread_cond_wait.c:655
#3  0x00007ffff1290a38 in pa_threaded_mainloop_wait () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ffff5d01f99 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#5  0x00007ffff5d06fe7 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#6  0x00007ffff3dbf7fc in start_thread (arg=0x7fff9c223700) at pthread_create.c:465
#7  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 17 (Thread 0x7fff9706a700 (LWP 27264)):
#0  0x00007ffff3ae0951 in __GI___poll (fds=0x7fff9000ca60, nfds=3, timeout=381) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff1290451 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007ffff1281e10 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007ffff12824a0 in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ffff1282530 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007ffff1290399 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fffee185ed8 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
#7  0x00007ffff3dbf7fc in start_thread (arg=0x7fff9706a700) at pthread_create.c:465
#8  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7fff9ffff700 (LWP 27257)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556b4cb24)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556b4cad0, cond=0x555556b4caf8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556b4caf8, mutex=0x555556b4cad0) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fff9ffff700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7fffbcb48700 (LWP 27252)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556ba18d8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556ba1888, cond=0x555556ba18b0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556ba18b0, mutex=0x555556ba1888) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fffbcb48700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fffbd349700 (LWP 27251)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556ba18d8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556ba1888, cond=0x555556ba18b0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556ba18b0, mutex=0x555556ba1888) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fffbd349700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fffbdb4a700 (LWP 27250)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556ba17f4)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556ba17a0, cond=0x555556ba17c8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556ba17c8, mutex=0x555556ba17a0) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fffbdb4a700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffbe34b700 (LWP 27249)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556ba17f4)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556ba17a0, cond=0x555556ba17c8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556ba17c8, mutex=0x555556ba17a0) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fffbe34b700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fffbeb4c700 (LWP 27248)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556ba17f4)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556ba17a0, cond=0x555556ba17c8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556ba17c8, mutex=0x555556ba17a0) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fffbeb4c700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fffbf34d700 (LWP 27247)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556bebc98)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556bebc48, cond=0x555556bebc70) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556bebc70, mutex=0x555556bebc48) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fffbf34d700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fffc02b6700 (LWP 27246)):
#0  0x00007ffff3dc6072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556b9e3ac)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556b9e358, cond=0x555556b9e380) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555556b9e380, mutex=0x555556b9e358) at pthread_cond_wait.c:655
#3  0x00007fffc4f530cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffc4f52de8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007ffff3dbf7fc in start_thread (arg=0x7fffc02b6700) at pthread_create.c:465
#6  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffe6354700 (LWP 27243)):
#0  0x00007ffff3dca060 in __libc_accept (fd=4, addr=..., len=0x0) at ../sysdeps/unix/sysv/linux/accept.c:26
#1  0x000055555592c1b9 in Sys::ReadSingletonSocket () at ./Daemon/src/engine/framework/System.cpp:242
#2  0x000055555592f09e in std::__invoke_impl<void, void (*)()> (__f=@0x5555569e7fd8: 0x55555592c18b <Sys::ReadSingletonSocket()>)
    at /usr/include/c++/7/bits/invoke.h:60
#3  0x000055555592eb55 in std::__invoke<void (*)()> (__fn=@0x5555569e7fd8: 0x55555592c18b <Sys::ReadSingletonSocket()>) at /usr/include/c++/7/bits/invoke.h:95
#4  0x000055555592feb2 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul> (this=0x5555569e7fd8) at /usr/include/c++/7/thread:234
#5  0x000055555592fe6e in std::thread::_Invoker<std::tuple<void (*)()> >::operator() (this=0x5555569e7fd8) at /usr/include/c++/7/thread:243
#6  0x000055555592fe3e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run (this=0x5555569e7fd0)
    at /usr/include/c++/7/thread:186
#7  0x00007ffff46000ff in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff3dbf7fc in start_thread (arg=0x7fffe6354700) at pthread_create.c:465
#9  0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffe6e24700 (LWP 27242)):
#0  0x00007ffff3ab0bf8 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffe6e23920, remaining=remaining@entry=0x7fffe6e23920)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:27
#1  0x00007ffff3ab0aea in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#2  0x000055555592c987 in Sys::SignalThread () at ./Daemon/src/engine/framework/System.cpp:373
#3  0x000055555592f09e in std::__invoke_impl<void, void (*)()> (__f=@0x5555569e7998: 0x55555592c864 <Sys::SignalThread()>)
    at /usr/include/c++/7/bits/invoke.h:60
#4  0x000055555592eb55 in std::__invoke<void (*)()> (__fn=@0x5555569e7998: 0x55555592c864 <Sys::SignalThread()>) at /usr/include/c++/7/bits/invoke.h:95
#5  0x000055555592feb2 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul> (this=0x5555569e7998) at /usr/include/c++/7/thread:234
#6  0x000055555592fe6e in std::thread::_Invoker<std::tuple<void (*)()> >::operator() (this=0x5555569e7998) at /usr/include/c++/7/thread:243
#7  0x000055555592fe3e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run (this=0x5555569e7990)
    at /usr/include/c++/7/thread:186
#8  0x00007ffff46000ff in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff3dbf7fc in start_thread (arg=0x7fffe6e24700) at pthread_create.c:465
#10 0x00007ffff3aecb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7f66a80 (LWP 27233)):
#0  0x00007ffff3dcae50 in __libc_recvmsg (fd=21, msg=0x7ffffffeced0, flags=0) at ../sysdeps/unix/sysv/linux/recvmsg.c:28
#1  0x000055555598edcd in NaClReceiveDatagram (handle=21, message=0x7ffffffecfd0, flags=0)
    at ./Daemon/libs/nacl/native_client/src/shared/imc/linux/nacl_imc.cc:168
#2  0x00005555558bec1b in IPC::InternalRecvMsg (handle=21, reader=...) at ./Daemon/src/common/IPC/Primitives.cpp:374
#3  0x00005555558bf232 in IPC::Socket::RecvMsg (this=0x555556234d80 <cgvm+128>)
    at ./Daemon/src/common/IPC/Primitives.cpp:457
#4  0x00005555556c6f7c in IPC::Channel::RecvMsg (this=0x555556234d80 <cgvm+128>)
    at ./Daemon/src/common/IPC/Channel.h:111
#5  0x00005555556c6ff7 in IPC::Channel::RecvReplyMsg (this=0x555556234d80 <cgvm+128>)
    at ./Daemon/src/common/IPC/Channel.h:121
#6  0x0000555555711cbd in IPC::detail::SendMsg<void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<> >>()::{lambda(unsigned int, Util::Reader)#1}&, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<>>(IPC::Channel&, void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<> >>()::{lambda(unsigned int, Util::Reader)#1}&, IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<> >) (channel=..., messageHandler=...)
    at ./Daemon/src/common/IPC/Channel.h:168
#7  0x000055555570e31a in IPC::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<> >, void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<> >>()::{lambda(unsigned int, Util::Reader)#1}>(IPC::Channel&, void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<> >>()::{lambda(unsigned int, Util::Reader)#1}&&) (
    channel=..., messageHandler=...) at ./Daemon/src/common/IPC/Channel.h:234
#8  0x000055555570bf94 in VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)2>>, IPC::Reply<> >>() (
    this=0x555556234d00 <cgvm>) at ./Daemon/src/engine/framework/VirtualMachine.h:136
#9  0x00005555556f420c in CGameVM::CGameShutdown (this=0x555556234d00 <cgvm>)
    at ./Daemon/src/engine/client/cl_cgame.cpp:1092
#10 0x00005555556f2c8d in CL_ShutdownCGame () at ./Daemon/src/engine/client/cl_cgame.cpp:324
#11 0x0000555555752c8c in CL_ShutdownAll () at ./Daemon/src/engine/client/cl_main.cpp:719
#12 0x0000555555752d09 in CL_FlushMemory () at ./Daemon/src/engine/client/cl_main.cpp:755
#13 0x0000555555754d56 in CL_DownloadsComplete () at ./Daemon/src/engine/client/cl_main.cpp:1854
#14 0x0000555555755142 in CL_InitDownloads () at ./Daemon/src/engine/client/cl_main.cpp:1996
#15 0x0000555555768181 in CL_ParseGamestate (msg=0x7ffffffedb20) at ./Daemon/src/engine/client/cl_parse.cpp:466
#16 0x0000555555768bd8 in CL_ParseServerMessage (msg=0x7ffffffedb20) at ./Daemon/src/engine/client/cl_parse.cpp:780
#17 0x0000555555757776 in CL_PacketEvent (from=..., msg=0x7ffffffedb20) at ./Daemon/src/engine/client/cl_main.cpp:2756
#18 0x0000555555663525 in HandlePacketEvent (event=...) at ./Daemon/src/engine/qcommon/common.cpp:925
#19 0x000055555566389d in Com_EventLoop () at ./Daemon/src/engine/qcommon/common.cpp:1024
#20 0x000055555566451f in Com_Frame () at ./Daemon/src/engine/qcommon/common.cpp:1518
#21 0x000055555576cd5b in Application::ClientApplication::Frame (this=0x55555625a020 <Application::GetApp()::app>)
    at ./Daemon/src/engine/client/ClientApplication.cpp:80
#22 0x00005555558f467c in Application::Frame () at ./Daemon/src/engine/framework/Application.cpp:75
#23 0x000055555592df75 in main (argc=24, argv=0x7fffffffde88) at ./Daemon/src/engine/framework/System.cpp:695
```

**Comment by slipher** [comment]
It looks like the Lua shutdown function is called before the general Rocket shutdown. The top function in the stack trace mentions Lua, so calling these shutdown functions in the reverse order might help. Or we could just not bother with calling shutdown functions at all, as ["the building is being demolished"](https://blogs.msdn.microsoft.com/oldnewthing/20120105-00/?p=8683). (When running as a DLL, this would cause memory to be leaked, but we do that elsewhere anyway).

**Comment by DolceTriade** [comment]
Lua should be shutdown before rocket. Rocket initializes Lua.

**Comment by illwieckz** [comment]
wait,

> 	// If the game crashes, Lua won't have been initialized it and will crash
> 	// if we try to shut it down.

what if it's what happen (because of another crash) but the test is flawed?
