### ISSUE TITLE
What is the need for `nacl_helper_bootstrap` on Linux?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1327]
What is the need for `nacl_helper_bootstrap` on Linux?

On my end the game runs without it.

**Comment by illwieckz** [comment]
I noticed it because FreeBSD can run the Linux binary on Linuxulator without the bootstrap, it also runs with the bootstrap. So I wondered if that was true on Linux too, it looks like it is.

**Comment by illwieckz** [comment]
@Kangz would you know what the help is for?

**Comment by Kangz** [comment]
The source is [here](https://source.chromium.org/chromium/chromium/src/+/main:native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c). It seems to be a custom dynamic loader that loads the NaCl ELF to set up part of the sandbox but I'm not sure how it is used, or what it does exactly.

**Comment by slipher** [comment]
There's a [test](https://source.chromium.org/chromium/chromium/src/+/main:native_client/src/trusted/service_runtime/linux/nacl_bootstrap_prereservation_test.c) that sheds some light on what it's supposed to do. Apparently the `reserved_at_zero` part is only expected to do anything on non-amd64 Linux.

One of the duties is to forbid memory mapping of some regions. Forbidding code to be mapped at certain regions is part of the secure sandboxing architecture. So you might not see something break but disabling it could let programs escape the sandbox.

**Comment by slipher** [comment]
Looks like the bootstrap responsibilities are:
- Map a lot of memory to give the desired address structure (only used on 32-bit arches)
- Set up some debug symbol thing that might be needed for nacl-gdb to work correctly. I haven't tested this.

So for the box64 case it works perfectly to skip this since the target arch is 64-bit and the debugger presumably wouldn't work anyway.

**Comment by illwieckz** [comment]
Thanks! This aligns with my research, where I was mostly guessing only two things were done:

- reserve some memory before calling `main()`,
- set-up some debug stuff.

The second thing (debug stuff), I had no idea what it could be, and I was even wondering if that was some chromium integration, wondering if we could just totally drop it if that would help us to make a static loader (see <https://github.com/DaemonEngine/native_client/issues/42>). If that can be used with `nacl-gdb` then it's welcome to keep it.

> Map a lot of memory to give the desired address structure (only used on 32-bit arches)
> So for the box64 case it works perfectly to skip this since the target arch is 64-bit and the debugger presumably wouldn't work anyway.

Very good to know! We indeed observed that amd64 nexe runs well on Linux without a bootstrap, and runs well on FreeBSD with Linuxulator without a bootstrap (I do believe we still run the bootstrap on it), and runs on box64 without the bootstrap (and box64 may not support the bootstrap mechanism to begin with), but I was wondering if we were just lucky. I was wondering for example if we were just lucky to use some wrongly mapped memory but large enough to not put the foot where it smells bad, or things like that.

So it's very good to know we can confidently disable the bootstrap on amd64, so we can disable it by default on every system that may not support gdb (like box64), and even just disable the bootstrap on amd64 when the gdb integration is disabled.

**Comment by slipher** [comment]
Actually I think the debugging thingy is for regular GDB, not nacl-gdb. nacl-gdb uses the RSP protocol: GDB doesn't ptrace or touch the NaCl process' memory directly. So sel_ldr can just tell GDB where the file is. But you might also want to debug sel_ldr (nacl_loader) itself, using native GDB. In that case maybe GDB would get confused because the process has replaced itself à la exec(2). For example `ps` shows `nacl_helper_bootstrap` for the loader. So the debugging thingy would help native GDB know what binary it is?

If I'm not mistaken, then keeping the x86-64 bootstrap loader for debugging is just a circular justification and there is truly no need to use it. The only thing it does for us is give assurance that we haven't broken the process chaining on other, rarely tested architectures by using the same code paths...

**Comment by illwieckz** [comment]
Interesting.

What else I would love to discover to be a circular justification is why the loader is a dynamic linked binary on Linux… Everything points out to the fact the dynamic linking is a hard requirement: they went to the annoyance of shipping libs for it to work under qemu in the `run.py` script to test foreign nexe… So for the common observator would assume “they knew what they were doing, so they likely had a very good reason to do so and bear that cost”, but maybe it was just cargo cult. We already know they can waste a lot of resources by storing multiple versions of archived and unarchived complete MinGW toolchains just because they need the MinGW AS. Sometime Principle Economy requires to consider that what may have driven someone else isn't Principle of Economy but Cargo Cult (the fact it may have cost more to someone, but the cost of choosing that choice was the least costly choice, disregarding the cost of execution itself.

**Comment by slipher** [comment]
> What else I would love to discover to be a circular justification is why the loader is a dynamic linked binary on Linux

The point being that by using a static binary, you would simplify bootstrapping by avoiding the need to load another executable and and having the original one replace itself? Yeah, that would make it somewhat simpler. But you would still need the custom `_start` to set up the address space before the CRT starts doing a bunch of initialization.

> they went to the annoyance of shipping libs for it to work under qemu in the `run.py` script to test foreign nexe

This objection doesn't make sense. If you want to test the ARM binaries in QEMU you need an ARM libc, regardless of how you link it.

Anyway the decision was made probably around 2010 so musl wasn't really a thing. And statically linking glibc has its well-known drawbacks. Maybe there wasn't as much confidence in stability of the Linux syscall ABI then. Last but not least, it would be weird to use a different libc than all the other Chrome binaries, which are obviously not going to a use a static glibc.

The main thing that annoys you personally is the multi-arch situation, but this was not a consideration for the devs at the time; the binaries always used the native architecture. (Well I did see one late reference to running on arm64 but this was when the project was already on life support, used for a few ChromeOS apps or whatever.)

**Comment by slipher** [comment]
I confirmed the purpose of the r_debug stuff: it's for debugging `sel_ldr` itself. When it's working, attaching GDB to the `nacl_helper_bootstrap` process gets you a valid stack trace like this:
```
#0  0x00007f5fd3a799ee in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f5fd3a6e668 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f5fd3a6ec8c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f5fd3a71158 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f5fd3c505b6 in NaClCondVarWait () from /unv/nacl/./scons-out/opt-linux-x86-64/staging/sel_ldr
#5  0x00007f5fd3c52e46 in NaClXCondVarWait () from /unv/nacl/./scons-out/opt-linux-x86-64/staging/sel_ldr
#6  0x00007f5fd3c2b70b in NaClWaitForMainThreadToExit () from /unv/nacl/./scons-out/opt-linux-x86-64/staging/sel_ldr
#7  0x00007f5fd3c1db98 in NaClSelLdrMain () from /unv/nacl/./scons-out/opt-linux-x86-64/staging/sel_ldr
#8  0x00007f5fd3a08ca8 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007f5fd3a08d65 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007f5fd3c1d031 in _start () from /unv/nacl/./scons-out/opt-linux-x86-64/staging/sel_ldr
```

But if the `--r_debug=xxxxxxx` argument is omitted from the command line, no symbols are found by GDB:
```
#0  0x00007fa5745519ee in ?? ()
#1  0x00007fa574546668 in ?? ()
#2  0x00007fa574a6e448 in ?? ()
#3  0x00000000ffffffff in ?? ()
#4  0x000000002e0d1b60 in ?? ()
#5  0x00007fa574546c8c in ?? ()
#6  0x00000000000000ca in ?? ()
#7  0x00007fa5748518b8 in ?? ()
#8  0x0000000000000000 in ?? ()
```

So nothing in the bootstrap loader is directly related to NaCl binaries. It has a *native* executable loader for doing an execless exec, and `r_debug` for native debugging.
