### ISSUE TITLE
segfault on macOS with dll cgame when doing substring

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#564]
_Moved from https://github.com/Unvanquished/Unvanquished/issues/1659_

When running dll cgame on macOS compiled with Apple clang, a crash occurs in `FS::Path::StripExtension` function.

The bug seems to occur when doing a substring with `return std::string(path.begin(), p - 1);` but does not occur if a logger is added within the loop containing this return:

```diff
std::string StripExtension(Str::StringRef path)
{
	if (path.empty())
		return "";
	if (path.back() == '/')
		return path.substr(path.size() - 1);

	// Find a dot or slash, searching from the end of the string
	for (const char* p = path.end(); p != path.begin(); p--) {
+		Log::Warn(":p %c", p);
		if (p[-1] == '/')
			return path;
		if (p[-1] == '.')
			return std::string(path.begin(), p - 1);
	}
	return path;
}
```

Extensive lldb log:

```
]cgame-native-dll.so was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 3479 stopped
* thread #9, stop reason = EXC_BAD_ACCESS (code=1, address=0x700009747000)
    frame #0: 0x000000013bb6f300 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::char_traits<char>::assign(__c1=0x0000700009736259, __c2=<unavailable>) at __string:208:73 [opt]
   205 	    typedef mbstate_t state_type;
   206 	
   207 	    static inline _LIBCPP_CONSTEXPR_AFTER_CXX14
-> 208 	    void assign(char_type& __c1, const char_type& __c2) _NOEXCEPT {__c1 = __c2;}
    	                                                                        ^
   209 	    static inline _LIBCPP_CONSTEXPR bool eq(char_type __c1, char_type __c2) _NOEXCEPT
   210 	            {return __c1 == __c2;}
   211 	    static inline _LIBCPP_CONSTEXPR bool lt(char_type __c1, char_type __c2) _NOEXCEPT
Target 0: (daemon) stopped.
thread backtrace
* thread #9, stop reason = EXC_BAD_ACCESS (code=1, address=0x700009747000)
  * frame #0: 0x000000013bb6f300 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::char_traits<char>::assign(__c1=0x0000700009736259, __c2=<unavailable>) at __string:208:73 [opt]
    frame #1: 0x000000013bb6f285 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::enable_if<__is_forward_iterator<char const*>::value, void>::type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2051 [opt]
    frame #2: 0x000000013bb6f214 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2060 [opt]
    frame #3: 0x000000013bb6f1fd cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2059 [opt]
    frame #4: 0x000000013bb6f1fd cgame-native-dll.so`FS::Path::StripExtension(path=<unavailable>) at FileSystem.cpp:531 [opt]
    frame #5: 0x000000013bb10de2 cgame-native-dll.so`BG_LoadEmoticons() at bg_misc.cpp:2544:22 [opt]
frame select 0
frame #0: 0x000000013bb6f300 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::char_traits<char>::assign(__c1=0x0000700009736259, __c2=<unavailable>) at __string:208:73 [opt]
   205 	    typedef mbstate_t state_type;
   206 	
   207 	    static inline _LIBCPP_CONSTEXPR_AFTER_CXX14
-> 208 	    void assign(char_type& __c1, const char_type& __c2) _NOEXCEPT {__c1 = __c2;}
    	                                                                        ^
   209 	    static inline _LIBCPP_CONSTEXPR bool eq(char_type __c1, char_type __c2) _NOEXCEPT
   210 	            {return __c1 == __c2;}
   211 	    static inline _LIBCPP_CONSTEXPR bool lt(char_type __c1, char_type __c2) _NOEXCEPT
frame variable
(std::__1::char_traits<char>::char_type &) __c1 = 0x0000700009736259 (&__c1 = 'g')
(const std::__1::char_traits<char>::char_type &) __c2 = <no location, value may have been optimized out>

frame select 1
frame #1: 0x000000013bb6f285 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::enable_if<__is_forward_iterator<char const*>::value, void>::type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2051 [opt]
   2048	        __set_long_size(__sz);
   2049	    }
   2050	    for (; __first != __last; ++__first, (void) ++__p)
-> 2051	        traits_type::assign(*__p, *__first);
   2052	    traits_type::assign(*__p, value_type());
   2053	}
   2054	
frame select 2
frame #2: 0x000000013bb6f214 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2060 [opt]
   2057	inline _LIBCPP_INLINE_VISIBILITY
   2058	basic_string<_CharT, _Traits, _Allocator>::basic_string(_InputIterator __first, _InputIterator __last)
   2059	{
-> 2060	    __init(__first, __last);
   2061	#if _LIBCPP_DEBUG_LEVEL >= 2
   2062	    __get_db()->__insert_c(this);
   2063	#endif
frame select 3
frame #3: 0x000000013bb6f1fd cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2059 [opt]
   2056	template<class _InputIterator>
   2057	inline _LIBCPP_INLINE_VISIBILITY
   2058	basic_string<_CharT, _Traits, _Allocator>::basic_string(_InputIterator __first, _InputIterator __last)
-> 2059	{
   2060	    __init(__first, __last);
   2061	#if _LIBCPP_DEBUG_LEVEL >= 2
   2062	    __get_db()->__insert_c(this);
frame select 4
frame #4: 0x000000013bb6f1fd cgame-native-dll.so`FS::Path::StripExtension(path=<unavailable>) at FileSystem.cpp:531 [opt]
   528 			if (p[-1] == '/')
   529 				return path;
   530 			if (p[-1] == '.')
-> 531 				return std::string(path.begin(), p - 1);
   532 		}
   533 		return path;
   534 	}
frame variable
(Str::StringRef) path = <no location, value may have been optimized out>

(const char *) p = <no location, value may have been optimized out>
```

Note: for some reasons the game does not compile as Debug build on my macOS dev environnement (cmake even fails to configure the compiler to begin with), so I only test with `RelWithDebInfo` builds.

**Comment by illwieckz** [comment]
On https://www.cplusplus.com/reference/string/string/string/ I read that constructor:

```c++
string (const char* s, size_t n);
```

But we do:

```
std::string(path.begin(), p - 1);
```

With `p` being an iterator iterated from `path.end()`:

```c++
for (const char* p = path.end(); p != path.begin(); p--)
```

So `p` does not look like to be a size but a pointer, right?

**Comment by illwieckz** [comment]
On the other hand that page also provides this example, that looks similar to what we do:

```c++
std::string s7 (s0.begin(), s0.begin()+7);
```

**Comment by illwieckz** [comment]
Maybe macOS compiler interprets `const char* p` as a number (then a size) instead of an iterator and then select the wrong constructor?

**Comment by illwieckz** [comment]
This non-ambiguous code seems to work on macOS:

```c++
return std::string(path.begin(), size_t(p - 1 - path.begin()));
```

And it strips extensions properly:

```
Warn: filename: dragoon.crn 
Warn: name: dragoon 
Warn: filename: medstat.crn 
Warn: name: medstat 
```

It also works on Linux.

**Comment by slipher** [comment]
`size_t` is NOT implicitly convertible from a pointer. The `(const char*, size_t)` constructor cannot be called with a pointer as the second argument.

Seeing that the results are affected by adding a printf, it looks like a typical memory corruption bug, where the stack or heap gets corrupted at some point. And then at some random later point depending on exact memory layout it may crash (or not). The bug is unlikely to be inside the StripExtension function.

**Comment by illwieckz** [comment]
Well, I'm lost with that issue, and my experience of macOS is that when it crashes the debug data is often meaningless. And to support what you says, on macOS it's more likely to crash where the issue is not than on Linux. It's also very common to get the crash far in some macOS subsystem like in #563, and I have seen many similar issues when porting NetRadiant to macOS where crashes happened far deep in Apple internals and stacktraces were unrelated to the code I commented out to workaround the bugs…

One interesting thing is that if I do:

```c++
return std::string(path.begin(), size_t(p - 1));
```

Instead of:

```c++
return std::string(path.begin(), p - 1);
```

The code compiles without warning but then the game crashes with out of memory error (which is not the same error as the original issue).

**Comment by illwieckz** [comment]
Note that adding log printfs before the for loop has no effect (same crash), adding a log printf in the for loop has an effect (no crash).

**Comment by necessarily-equal** [comment]
Maybe we should change the title to hint at a memory corruption instead?

**Comment by slipher** [comment]
I can reproduce misbehavior around the same spot. On my machine it manifests as 

```
Warn: Conflicting emoticon images found: emoticons/hive.crn and emoticons/hive.crn 
Warn: Conflicting emoticon images found: emoticons/hovel.crn and emoticons/hovel.crn 
Warn: Conflicting emoticon images found: emoticons/bot.crn and emoticons/bot.crn 
Warn: Conflicting emoticon images found: emoticons/overmind.crn and emoticons/overmind.crn 
Warn: Conflicting emoticon images found: emoticons/grenade.crn and emoticons/grenade.crn 
Warn: Conflicting emoticon images found: emoticons/prifle.crn and emoticons/prifle.crn 
Warn: Conflicting emoticon images found: emoticons/tesla.crn and emoticons/tesla.crn 
Warn: Conflicting emoticon images found: emoticons/dev.crn and emoticons/dev.crn 
Warn: Conflicting emoticon images found: emoticons/acidtube.crn and emoticons/acidtube.crn 
Warn: Conflicting emoticon images found: emoticons/cross.crn and emoticons/cross.crn [further messages like this will be suppressed] 
```

Debugging now.

**Comment by slipher** [comment]
Never mind, the above log is arising from a different problem: the cgame DLL doesn't get unloaded upon cgame restart. Although that is something with a lot of potential to cause undefined behaviors...

**Comment by slipher** [comment]
So I guess I can't reproduce anything on my machine (Clang 13.0.0), but it may be worth checking whether #577 makes it go away.

**Comment by illwieckz** [comment]
It looks like it's still there:

```
Loading VM module build/game/default-darwin-amd64-clang-nolto-reldeb-dll/cgame-native-dll.so... 
Loaded cgame VM module in 134 msec 
]cgame-native-dll.so was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 6502 stopped
* thread #4, stop reason = EXC_BAD_ACCESS (code=1, address=0x70000f09b000)
    frame #0: 0x00000001318c7c00 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::char_traits<char>::assign(__c1=0x000070000f08c1c9, __c2=<unavailable>) at __string:208:75 [opt]
   205 	    typedef mbstate_t state_type;
   206 	
   207 	    static inline _LIBCPP_CONSTEXPR_AFTER_CXX14
-> 208 	    void assign(char_type& __c1, const char_type& __c2) _NOEXCEPT {__c1 = __c2;}
   209 	    static inline _LIBCPP_CONSTEXPR bool eq(char_type __c1, char_type __c2) _NOEXCEPT
   210 	            {return __c1 == __c2;}
   211 	    static inline _LIBCPP_CONSTEXPR bool lt(char_type __c1, char_type __c2) _NOEXCEPT
Target 0: (daemon-tty) stopped.

Process 6502 launched: 'build/engine/default-darwin-amd64-clang-nolto-reldeb-exe/daemon-tty' (x86_64)
(lldb) thread backtrace all
  thread #1, queue = 'com.apple.main-thread'
    frame #0: 0x00007fff72f19786 libsystem_kernel.dylib`__recvmsg + 10
    frame #1: 0x0000000100155ca0 daemon-tty`::NaClReceiveDatagram(handle=<unavailable>, message=<unavailable>, flags=<unavailable>) at nacl_imc.cc:341:23 [opt]
    frame #2: 0x00000001000b7dcc daemon-tty`IPC::InternalRecvMsg(handle=10, reader=0x00007ffeefbff0f0) at Primitives.cpp:384:15 [opt]
    frame #3: 0x00000001000b852b daemon-tty`IPC::Socket::RecvMsg(this=0x0000000100aab830) const at Primitives.cpp:474:9 [opt]
    frame #4: 0x000000010006cdb6 daemon-tty`void IPC::detail::SendMsg<void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader)&, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<>, glconfig_t&>(IPC::Channel&, void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader)&, IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&) [inlined] IPC::Channel::RecvMsg() const at Channel.h:111:27 [opt]
    frame #5: 0x000000010006cda7 daemon-tty`void IPC::detail::SendMsg<void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader)&, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<>, glconfig_t&>(IPC::Channel&, void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader)&, IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&) [inlined] IPC::Channel::RecvReplyMsg() at Channel.h:121 [opt]
    frame #6: 0x000000010006cda7 daemon-tty`void IPC::detail::SendMsg<void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader)&, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<>, glconfig_t&>(channel=0x0000000100aab830, messageHandler=0x00007ffeefbff178, (null)=<unavailable>, args=<unavailable>)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader)&, IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&) at Channel.h:168 [opt]
    frame #7: 0x000000010005804b daemon-tty`CGameVM::CGameRocketInit() [inlined] void IPC::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader), glconfig_t&>(channel=<unavailable>, messageHandler=0x0000000100aab798, args=<unavailable>)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(glconfig_t&)::'lambda'(unsigned int, Util::Reader)&&, glconfig_t&) at Channel.h:234:9 [opt]
    frame #8: 0x000000010005803b daemon-tty`CGameVM::CGameRocketInit() [inlined] void VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)9>, glconfig_t>, IPC::Reply<> >, glconfig_t&>(this=0x0000000100aab798, args=<unavailable>) at VirtualMachine.h:136 [opt]
    frame #9: 0x000000010005801a daemon-tty`CGameVM::CGameRocketInit(this=0x0000000100aab798) at cl_cgame.cpp:1041 [opt]
    frame #10: 0x00000001000fac8f daemon-tty`main [inlined] Sys::Init(argc=<unavailable>, argv=<unavailable>) at System.cpp:812:2 [opt]
    frame #11: 0x00000001000f9811 daemon-tty`main(argc=<unavailable>, argv=<unavailable>) at System.cpp:832 [opt]
    frame #12: 0x00007fff72ddf3d5 libdyld.dylib`start + 1
    frame #13: 0x00007fff72ddf3d5 libdyld.dylib`start + 1
  thread #2
    frame #0: 0x00007fff72f17f2e libsystem_kernel.dylib`__semwait_signal + 10
    frame #1: 0x00007fff72ea3914 libsystem_c.dylib`nanosleep + 199
    frame #2: 0x00007fff72ea3776 libsystem_c.dylib`sleep + 41
    frame #3: 0x00000001000fc83a daemon-tty`Sys::SignalThread() at System.cpp:474:3 [opt]
    frame #4: 0x00000001000fd228 daemon-tty`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) [inlined] decltype(__f=<unavailable>)()>(fp)()) std::__1::__invoke<void (*)()>(void (*&&)()) at type_traits:4339:1 [opt]
    frame #5: 0x00000001000fd224 daemon-tty`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) [inlined] void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>(__t=<unavailable>)()>&, std::__1::__tuple_indices<>) at thread:342 [opt]
    frame #6: 0x00000001000fd224 daemon-tty`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(__vp=0x0000000101212770) at thread:352 [opt]
    frame #7: 0x00007fff72fd32eb libsystem_pthread.dylib`_pthread_body + 126
    frame #8: 0x00007fff72fd6249 libsystem_pthread.dylib`_pthread_start + 66
    frame #9: 0x00007fff72fd240d libsystem_pthread.dylib`thread_start + 13
  thread #3
    frame #0: 0x00007fff72f181e6 libsystem_kernel.dylib`__accept + 10
    frame #1: 0x00000001000f9321 daemon-tty`Sys::ReadSingletonSocket() at System.cpp:268:14 [opt]
    frame #2: 0x00000001000fd228 daemon-tty`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) [inlined] decltype(__f=<unavailable>)()>(fp)()) std::__1::__invoke<void (*)()>(void (*&&)()) at type_traits:4339:1 [opt]
    frame #3: 0x00000001000fd224 daemon-tty`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) [inlined] void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>(__t=<unavailable>)()>&, std::__1::__tuple_indices<>) at thread:342 [opt]
    frame #4: 0x00000001000fd224 daemon-tty`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(__vp=0x0000000101212a30) at thread:352 [opt]
    frame #5: 0x00007fff72fd32eb libsystem_pthread.dylib`_pthread_body + 126
    frame #6: 0x00007fff72fd6249 libsystem_pthread.dylib`_pthread_start + 66
    frame #7: 0x00007fff72fd240d libsystem_pthread.dylib`thread_start + 13
* thread #4, stop reason = EXC_BAD_ACCESS (code=1, address=0x70000f09b000)
  * frame #0: 0x00000001318c7c00 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::char_traits<char>::assign(__c1=0x000070000f08c1c9, __c2=<unavailable>) at __string:208:75 [opt]
    frame #1: 0x00000001318c7b05 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::enable_if<__is_forward_iterator<char const*>::value, void>::type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2051 [opt]
    frame #2: 0x00000001318c7a94 cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2060 [opt]
    frame #3: 0x00000001318c7a7d cgame-native-dll.so`FS::Path::StripExtension(Str::BasicStringRef<char>) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<char const*>(this=<unavailable>, __first=<unavailable>, __last=<unavailable>) at string:2059 [opt]
    frame #4: 0x00000001318c7a7d cgame-native-dll.so`FS::Path::StripExtension(path=<unavailable>) at FileSystem.cpp:541 [opt]
    frame #5: 0x000000013184b50f cgame-native-dll.so`BG_LoadEmoticons() at bg_misc.cpp:2428:22 [opt]
```

**Comment by illwieckz** [comment]
ASAN doesn't help:

```
==10843==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee63835a0 at pc 0x000109ca0f39 bp 0x7ffee6383480 sp 0x7ffee6383478
WRITE of size 16 at 0x7ffee63835a0 thread T0
    #0 0x109ca0f38 in FS::Path::StripExtension(Str::BasicStringRef<char>) (build/game/default-darwin-amd64-clang-nolto-reldeb-exe/cgame-native-exe:x86_64+0x100434f38)
    #1 0x109aec04c in BG_LoadEmoticons() (build/game/default-darwin-amd64-clang-nolto-reldeb-exe/cgame-native-exe:x86_64+0x10028004c)
    #2 0x109983f95 in CG_Rocket_Init(glconfig_t) (build/game/default-darwin-amd64-clang-nolto-reldeb-exe/cgame-native-exe:x86_64+0x100117f95)
    #3 0x10987fa38 in VM::VMHandleSyscall(unsigned int, Util::Reader) (build/game/default-darwin-amd64-clang-nolto-reldeb-exe/cgame-native-exe:x86_64+0x100013a38)
    #4 0x109c8c328 in main (build/game/default-darwin-amd64-clang-nolto-reldeb-exe/cgame-native-exe:x86_64+0x100420328)
    #5 0x7fff72ddf3d4 in start (/usr/lib/system/libdyld.dylib:x86_64+0x163d4)

Address 0x7ffee63835a0 is located in stack of thread T0 at offset 192 in frame
    #0 0x109aebe1f in BG_LoadEmoticons() (build/game/default-darwin-amd64-clang-nolto-reldeb-exe/cgame-native-exe:x86_64+0x10027fe1f)

  This frame has 4 object(s):
    [32, 36) 'count' (line 2425)
    [48, 120) 'ref.tmp' (line 2426)
    [160, 184) 'name' (line 2428) <== Memory access at offset 192 overflows this variable
    [224, 248) 'ref.tmp26' (line 2439)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (build/game/default-darwin-amd64-clang-nolto-reldeb-exe/cgame-native-exe:x86_64+0x100434f38) in FS::Path::StripExtension(Str::BasicStringRef<char>)
Shadow bytes around the buggy address:
  0x1fffdcc70660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdcc70670: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdcc70680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Warn: Error during initialization: CGame VM: Crashed with signal 6: Abort trap: 6 
```

**Comment by illwieckz** [comment]
So it says `Memory access at offset 192 overflows this variable` but the string is `unv.crn`…

**Comment by illwieckz** [comment]
Now it says `Memory access at offset 224 overflows this variable`, the offset is random.

**Comment by illwieckz** [comment]
Also the line is:

```c++
std::string name = FS::Path::StripExtension( filename );
```

How can it be possible that `name` is overflown?

**Comment by slipher** [comment]
Are you still using Clang 10.0? That must be very outdated now.
