### ISSUE TITLE
Engine crashes in error window if there is no display.

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#984]
This is minor because if we can't render the game and can't render the error window, the user can't see anything anywyay, but the engine should not crash but shutdown properly instead.

To reproduce this error I accumulated (after the build of the code catching and reporting the GLVND bug):

- GLVND linux build,
- OGLP amdgpu-pro OpenGL driver that is incompatible with GLVND,
- `DISPLAY=:42` to set an unavailable display.

```gdb
--- Common Initialization Complete ---
Calling GetRefAPI…
SDL_Init( SDL_INIT_VIDEO )...
Using SDL version 2.28.3
SDL using driver "offscreen"
Using OpenGL ABI "GLVND"
Initializing OpenGL display
Using GLEW version 2.2.0
Display aspect: 1.333
...setting mode -1: 2560×1440
[New Thread 0x7fffc9d986c0 (LWP 2732133)]
Warn: SDL returned a broken OpenGL context.

Please report the bug and tell us what is your operating system,
OpenGL driver, graphic card, and if you built the game yourself.

This engine was built with the "GLVND" OpenGL ABI,
try to reconfigure the build with the "LEGACY" one:

  cmake -DOpenGL_GL_PREFERENCE=LEGACY

See: https://github.com/DaemonEngine/Daemon/issues/945
][Detaching after fork from child process 2732134]
[Detaching after fork from child process 2732135]

(zenity:2732135): Gtk-WARNING **: 03:36:29.876: cannot open display: :42

Thread 1 "daemon" received signal SIGSEGV, Segmentation fault.
__GI_____strtol_l_internal (nptr=nptr@entry=0x0, endptr=endptr@entry=0x7fffffffc188, base=base@entry=10, group=group@entry=0, bin_cst=bin_cst@entry=true, loc=0x7ffff6fff5a0 <_nl_global_locale>) at ../stdlib/strtol_l.c:304
Download failed: Argument invalide.  Continuing without source file ./stdlib/../stdlib/strtol_l.c.
304	../stdlib/strtol_l.c: Aucun fichier ou dossier de ce type.

Thread 4 (Thread 0x7fffc9d986c0 (LWP 2732133) "daemon"):
#0  0x00007ffff6e94076 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fffca6eb6a0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7fffca6eb6a0) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7fffca6eb6a0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6e969fe in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fffca6eb650, cond=0x7fffca6eb678) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x7fffca6eb678, mutex=0x7fffca6eb650) at ./nptl/pthread_cond_wait.c:627
#5  0x00007ffff30804a0 in ?? () from /opt/amdgpu/lib/x86_64-linux-gnu/dri/amdgpu_dri.so
#6  0x00007ffff1a0844b in ?? () from /opt/amdgpu/lib/x86_64-linux-gnu/dri/amdgpu_dri.so
#7  0x00007ffff30b5e74 in ?? () from /opt/amdgpu/lib/x86_64-linux-gnu/dri/amdgpu_dri.so
#8  0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#9  0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 3 (Thread 0x7fffef5ff6c0 (LWP 2732132) "daemon"):
#0  0x00007ffff6f2a01f in __libc_accept (fd=4, addr=..., len=0x0) at ../sysdeps/unix/sysv/linux/accept.c:26
#1  0x000055555572e710 in Sys::ReadSingletonSocket () at Unvanquished/daemon/src/engine/framework/System.cpp:246
#2  0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x5555567cb8f0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#3  0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#4  0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 2 (Thread 0x7ffff054d6c0 (LWP 2732131) "daemon"):
#0  0x00007ffff6ee56f1 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffff054ca10, rem=rem@entry=0x7ffff054ca10) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007ffff6ef9937 in __GI___nanosleep (req=req@entry=0x7ffff054ca10, rem=rem@entry=0x7ffff054ca10) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00007ffff6f0e2ae in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x0000555555730a2a in Sys::SignalThread () at Unvanquished/daemon/src/engine/framework/System.cpp:389
#4  0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x5555567fc620) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#5  0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#6  0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7ffff54fea80 (LWP 2732128) "daemon"):
#0  __GI_____strtol_l_internal (nptr=nptr@entry=0x0, endptr=endptr@entry=0x7fffffffc188, base=base@entry=10, group=group@entry=0, bin_cst=bin_cst@entry=true, loc=0x7ffff6fff5a0 <_nl_global_locale>) at ../stdlib/strtol_l.c:304
#1  0x00007ffff6e5113c in __GI___isoc23_strtol (nptr=nptr@entry=0x0, endptr=endptr@entry=0x7fffffffc188, base=base@entry=10) at ../stdlib/strtol.c:126
#2  0x00007ffff7e07561 in SDL_strtol_REAL (base=10, endp=0x7fffffffc188, string=0x0) at /usr/src/libsdl2-2.28.3+dfsg-2/src/stdlib/SDL_string.c:898
#3  get_zenity_version (minor=<synthetic pointer>, major=<synthetic pointer>) at /usr/src/libsdl2-2.28.3+dfsg-2/src/video/wayland/SDL_waylandmessagebox.c:103
#4  Wayland_ShowMessageBox (buttonid=0x7fffffffc184, messageboxdata=0x7fffffffc190) at /usr/src/libsdl2-2.28.3+dfsg-2/src/video/wayland/SDL_waylandmessagebox.c:137
#5  SDL_ShowMessageBox_REAL (messageboxdata=0x7fffffffc190, buttonid=0x7fffffffc184) at /usr/src/libsdl2-2.28.3+dfsg-2/src/video/SDL_video.c:4495
#6  0x00007ffff7dfd24b in SDL_ShowMessageBox_REAL (buttonid=0x0, messageboxdata=0x7fffffffc350) at /usr/src/libsdl2-2.28.3+dfsg-2/src/video/SDL_video.c:4407
#7  SDL_ShowSimpleMessageBox_REAL (flags=<optimized out>, title=<optimized out>, message=<optimized out>, window=<optimized out>) at /usr/src/libsdl2-2.28.3+dfsg-2/src/video/SDL_video.c:4582
#8  0x000055555558b854 in Application::ClientApplication::Shutdown (this=<optimized out>, error=true, message=...) at Unvanquished/daemon/src/engine/client/ClientApplication.cpp:115
#9  0x000055555572ea68 in Sys::Shutdown (error=true, message=...) at Unvanquished/daemon/src/engine/framework/System.cpp:288
#10 0x000055555572eb3b in Sys::Error (message=...) at Unvanquished/daemon/src/engine/framework/System.cpp:335
#11 0x00005555556d7917 in GLimp_CreateContext (configuration=...) at Unvanquished/daemon/src/engine/sys/sdl_glimp.cpp:785
#12 0x00005555556d67ad in GLimp_ValidateBestContext (GLEWmajor=2, bestValidatedConfiguration=..., extendedValidationConfiguration=...) at Unvanquished/daemon/src/engine/sys/sdl_glimp.cpp:1010
#13 GLimp_SetMode (mode=<optimized out>, fullscreen=false, bordered=false) at Unvanquished/daemon/src/engine/sys/sdl_glimp.cpp:1393
#14 GLimp_StartDriverAndSetMode (mode=<optimized out>, fullscreen=false, bordered=false) at Unvanquished/daemon/src/engine/sys/sdl_glimp.cpp:1539
#15 0x00005555556d4f39 in GLimp_Init () at Unvanquished/daemon/src/engine/sys/sdl_glimp.cpp:1969
#16 0x000055555568ffd2 in InitOpenGL () at Unvanquished/daemon/src/engine/renderer/tr_init.cpp:307
#17 R_Init () at Unvanquished/daemon/src/engine/renderer/tr_init.cpp:1414
#18 0x000055555569eab0 in RE_BeginRegistration (glconfigOut=0xa, glconfig2Out=0x7fffffffc188) at Unvanquished/daemon/src/engine/renderer/tr_model.cpp:259
#19 0x00005555555f0c8f in CL_InitRenderer () at Unvanquished/daemon/src/engine/client/cl_main.cpp:2134
#20 0x00005555555efc11 in CL_StartHunkUsers () at Unvanquished/daemon/src/engine/client/cl_main.cpp:2208
#21 0x0000555555730218 in Sys::Init (argc=<optimized out>, argv=<optimized out>) at Unvanquished/daemon/src/engine/framework/System.cpp:721
#22 main (argc=<optimized out>, argv=<optimized out>) at Unvanquished/daemon/src/engine/framework/System.cpp:741
```

**Comment by illwieckz** [comment]
We may have not fix for this one and the bug may be in SDL anyway.

This thread is just to not forget™.
